// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facebook_pages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFacebookPageInventory = `-- name: CountFacebookPageInventory :one
SELECT COUNT(DISTINCT p.id)
FROM facebook_pages p
JOIN facebook_page_connections pc ON pc.page_id = p.id
JOIN facebook_connections c ON c.id = pc.connection_id
    AND c.user_id = $1 AND c.revoked_at IS NULL
WHERE ($2 = '00000000-0000-0000-0000-000000000000'::uuid OR c.id = $2)
  AND ($3::text = '' OR p.name ILIKE '%' || $3::text || '%' OR p.facebook_page_id ILIKE '%' || $3::text || '%')
`

type CountFacebookPageInventoryParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Column3 string      `json:"column_3"`
}

func (q *Queries) CountFacebookPageInventory(ctx context.Context, arg CountFacebookPageInventoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFacebookPageInventory, arg.UserID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedFacebookPageListings = `-- name: CountPublishedFacebookPageListings :one
SELECT COUNT(*)
FROM facebook_page_listings l
JOIN facebook_pages p ON p.id = l.page_id AND p.is_active = TRUE
WHERE l.status = 'published'
  AND ($1::text = '' OR l.title ILIKE '%' || $1::text || '%' OR p.name ILIKE '%' || $1::text || '%'
       OR p.facebook_page_id ILIKE '%' || $1::text || '%')
  AND EXISTS (
      SELECT 1
      FROM facebook_page_connections pc
      JOIN facebook_connections c ON c.id = pc.connection_id
      WHERE pc.page_id = l.page_id
        AND c.user_id = l.seller_user_id
        AND c.revoked_at IS NULL
  )
`

func (q *Queries) CountPublishedFacebookPageListings(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedFacebookPageListings, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFacebookPageForUser = `-- name: GetFacebookPageForUser :one
SELECT p.id, p.facebook_page_id, p.name, p.category, p.picture_url, p.is_active,
       p.last_synced_at, p.created_at, p.updated_at,
       c.id AS connection_id, c.user_id AS connection_user_id
FROM facebook_pages p
JOIN facebook_page_connections pc ON pc.page_id = p.id
JOIN facebook_connections c ON c.id = pc.connection_id
    AND c.user_id = $2 AND c.revoked_at IS NULL
WHERE p.id = $1
ORDER BY pc.last_seen_at DESC
LIMIT 1
`

type GetFacebookPageForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetFacebookPageForUserRow struct {
	ID               uuid.UUID          `json:"id"`
	FacebookPageID   string             `json:"facebook_page_id"`
	Name             string             `json:"name"`
	Category         pgtype.Text        `json:"category"`
	PictureUrl       pgtype.Text        `json:"picture_url"`
	IsActive         bool               `json:"is_active"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ConnectionID     uuid.UUID          `json:"connection_id"`
	ConnectionUserID uuid.UUID          `json:"connection_user_id"`
}

func (q *Queries) GetFacebookPageForUser(ctx context.Context, arg GetFacebookPageForUserParams) (GetFacebookPageForUserRow, error) {
	row := q.db.QueryRow(ctx, getFacebookPageForUser, arg.ID, arg.UserID)
	var i GetFacebookPageForUserRow
	err := row.Scan(
		&i.ID,
		&i.FacebookPageID,
		&i.Name,
		&i.Category,
		&i.PictureUrl,
		&i.IsActive,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConnectionID,
		&i.ConnectionUserID,
	)
	return i, err
}

const getPublishedFacebookPageListing = `-- name: GetPublishedFacebookPageListing :one
SELECT l.id, l.page_id, p.facebook_page_id, p.name, l.title, l.subtitle,
       l.description, l.price_usd::double precision AS price_usd, l.currency, l.delivery_window, l.status,
       l.featured, l.sort_order, l.created_at, l.updated_at, l.published_at
FROM facebook_page_listings l
JOIN facebook_pages p ON p.id = l.page_id AND p.is_active = TRUE
WHERE l.id = $1 AND l.status = 'published'
  AND EXISTS (
      SELECT 1
      FROM facebook_page_connections pc
      JOIN facebook_connections c ON c.id = pc.connection_id
      WHERE pc.page_id = l.page_id
        AND c.user_id = l.seller_user_id
        AND c.revoked_at IS NULL
  )
`

type GetPublishedFacebookPageListingRow struct {
	ID             uuid.UUID          `json:"id"`
	PageID         uuid.UUID          `json:"page_id"`
	FacebookPageID string             `json:"facebook_page_id"`
	Name           string             `json:"name"`
	Title          string             `json:"title"`
	Subtitle       string             `json:"subtitle"`
	Description    string             `json:"description"`
	PriceUsd       float64            `json:"price_usd"`
	Currency       string             `json:"currency"`
	DeliveryWindow string             `json:"delivery_window"`
	Status         string             `json:"status"`
	Featured       bool               `json:"featured"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetPublishedFacebookPageListing(ctx context.Context, id uuid.UUID) (GetPublishedFacebookPageListingRow, error) {
	row := q.db.QueryRow(ctx, getPublishedFacebookPageListing, id)
	var i GetPublishedFacebookPageListingRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.FacebookPageID,
		&i.Name,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.PriceUsd,
		&i.Currency,
		&i.DeliveryWindow,
		&i.Status,
		&i.Featured,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const linkFacebookPageToConnection = `-- name: LinkFacebookPageToConnection :exec
INSERT INTO facebook_page_connections (page_id, connection_id, last_seen_at)
VALUES ($1, $2, NOW())
ON CONFLICT (page_id, connection_id) DO UPDATE
SET last_seen_at = NOW()
`

type LinkFacebookPageToConnectionParams struct {
	PageID       uuid.UUID `json:"page_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

func (q *Queries) LinkFacebookPageToConnection(ctx context.Context, arg LinkFacebookPageToConnectionParams) error {
	_, err := q.db.Exec(ctx, linkFacebookPageToConnection, arg.PageID, arg.ConnectionID)
	return err
}

const listFacebookPageInventory = `-- name: ListFacebookPageInventory :many
SELECT DISTINCT ON (p.id)
    p.id, p.facebook_page_id, p.name, p.category, p.picture_url, p.is_active,
    p.last_synced_at, p.created_at, p.updated_at,
    c.id AS connection_id, c.facebook_user_name AS connection_name,
    l.id AS listing_id, l.title AS listing_title, l.subtitle AS listing_subtitle,
    l.description AS listing_description, COALESCE(l.price_usd, 0)::double precision AS price_usd, l.currency,
    l.delivery_window, l.status AS listing_status, l.featured, l.sort_order,
    l.published_at
FROM facebook_pages p
JOIN facebook_page_connections pc ON pc.page_id = p.id
JOIN facebook_connections c ON c.id = pc.connection_id
    AND c.user_id = $1 AND c.revoked_at IS NULL
LEFT JOIN facebook_page_listings l ON l.page_id = p.id AND l.seller_user_id = $1
WHERE ($2 = '00000000-0000-0000-0000-000000000000'::uuid OR c.id = $2)
  AND ($3::text = '' OR p.name ILIKE '%' || $3::text || '%' OR p.facebook_page_id ILIKE '%' || $3::text || '%')
ORDER BY p.id, pc.last_seen_at DESC
LIMIT $4 OFFSET $5
`

type ListFacebookPageInventoryParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Column3 string      `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListFacebookPageInventoryRow struct {
	ID                 uuid.UUID          `json:"id"`
	FacebookPageID     string             `json:"facebook_page_id"`
	Name               string             `json:"name"`
	Category           pgtype.Text        `json:"category"`
	PictureUrl         pgtype.Text        `json:"picture_url"`
	IsActive           bool               `json:"is_active"`
	LastSyncedAt       pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ConnectionID       uuid.UUID          `json:"connection_id"`
	ConnectionName     string             `json:"connection_name"`
	ListingID          pgtype.UUID        `json:"listing_id"`
	ListingTitle       pgtype.Text        `json:"listing_title"`
	ListingSubtitle    pgtype.Text        `json:"listing_subtitle"`
	ListingDescription pgtype.Text        `json:"listing_description"`
	PriceUsd           float64            `json:"price_usd"`
	Currency           pgtype.Text        `json:"currency"`
	DeliveryWindow     pgtype.Text        `json:"delivery_window"`
	ListingStatus      pgtype.Text        `json:"listing_status"`
	Featured           pgtype.Bool        `json:"featured"`
	SortOrder          pgtype.Int4        `json:"sort_order"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListFacebookPageInventory(ctx context.Context, arg ListFacebookPageInventoryParams) ([]ListFacebookPageInventoryRow, error) {
	rows, err := q.db.Query(ctx, listFacebookPageInventory,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacebookPageInventoryRow{}
	for rows.Next() {
		var i ListFacebookPageInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FacebookPageID,
			&i.Name,
			&i.Category,
			&i.PictureUrl,
			&i.IsActive,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConnectionID,
			&i.ConnectionName,
			&i.ListingID,
			&i.ListingTitle,
			&i.ListingSubtitle,
			&i.ListingDescription,
			&i.PriceUsd,
			&i.Currency,
			&i.DeliveryWindow,
			&i.ListingStatus,
			&i.Featured,
			&i.SortOrder,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedFacebookPageListings = `-- name: ListPublishedFacebookPageListings :many
SELECT l.id, l.page_id, p.facebook_page_id, p.name, l.title, l.subtitle,
       l.description, l.price_usd::double precision AS price_usd, l.currency, l.delivery_window, l.status,
       l.featured, l.sort_order, l.created_at, l.updated_at, l.published_at
FROM facebook_page_listings l
JOIN facebook_pages p ON p.id = l.page_id AND p.is_active = TRUE
WHERE l.status = 'published'
  AND ($1::text = '' OR l.title ILIKE '%' || $1::text || '%' OR p.name ILIKE '%' || $1::text || '%'
       OR p.facebook_page_id ILIKE '%' || $1::text || '%')
  AND EXISTS (
      SELECT 1
      FROM facebook_page_connections pc
      JOIN facebook_connections c ON c.id = pc.connection_id
      WHERE pc.page_id = l.page_id
        AND c.user_id = l.seller_user_id
        AND c.revoked_at IS NULL
  )
ORDER BY l.featured DESC, l.sort_order, l.published_at DESC, l.id DESC
LIMIT $2 OFFSET $3
`

type ListPublishedFacebookPageListingsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListPublishedFacebookPageListingsRow struct {
	ID             uuid.UUID          `json:"id"`
	PageID         uuid.UUID          `json:"page_id"`
	FacebookPageID string             `json:"facebook_page_id"`
	Name           string             `json:"name"`
	Title          string             `json:"title"`
	Subtitle       string             `json:"subtitle"`
	Description    string             `json:"description"`
	PriceUsd       float64            `json:"price_usd"`
	Currency       string             `json:"currency"`
	DeliveryWindow string             `json:"delivery_window"`
	Status         string             `json:"status"`
	Featured       bool               `json:"featured"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListPublishedFacebookPageListings(ctx context.Context, arg ListPublishedFacebookPageListingsParams) ([]ListPublishedFacebookPageListingsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedFacebookPageListings, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedFacebookPageListingsRow{}
	for rows.Next() {
		var i ListPublishedFacebookPageListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.FacebookPageID,
			&i.Name,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.PriceUsd,
			&i.Currency,
			&i.DeliveryWindow,
			&i.Status,
			&i.Featured,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFacebookPage = `-- name: UpsertFacebookPage :one
INSERT INTO facebook_pages (
    id, facebook_page_id, name, last_synced_at, is_active
)
VALUES ($1, $2, $3, NOW(), TRUE)
ON CONFLICT (facebook_page_id) DO UPDATE
SET name = EXCLUDED.name,
    is_active = TRUE,
    last_synced_at = NOW(),
    updated_at = NOW()
RETURNING id, facebook_page_id, name, category, picture_url, is_active,
          last_synced_at, created_at, updated_at
`

type UpsertFacebookPageParams struct {
	ID             uuid.UUID `json:"id"`
	FacebookPageID string    `json:"facebook_page_id"`
	Name           string    `json:"name"`
}

func (q *Queries) UpsertFacebookPage(ctx context.Context, arg UpsertFacebookPageParams) (FacebookPage, error) {
	row := q.db.QueryRow(ctx, upsertFacebookPage, arg.ID, arg.FacebookPageID, arg.Name)
	var i FacebookPage
	err := row.Scan(
		&i.ID,
		&i.FacebookPageID,
		&i.Name,
		&i.Category,
		&i.PictureUrl,
		&i.IsActive,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFacebookPageListing = `-- name: UpsertFacebookPageListing :one
INSERT INTO facebook_page_listings (
    id, page_id, seller_user_id, title, subtitle, description, price_usd,
    currency, delivery_window, status, featured, sort_order, published_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7::double precision, $8, $9, $10, $11, $12,
        CASE WHEN $10::varchar = 'published' THEN NOW() ELSE NULL END)
ON CONFLICT (page_id) DO UPDATE
SET title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    price_usd = EXCLUDED.price_usd,
    currency = EXCLUDED.currency,
    delivery_window = EXCLUDED.delivery_window,
    status = EXCLUDED.status,
    featured = EXCLUDED.featured,
    sort_order = EXCLUDED.sort_order,
    published_at = CASE
        WHEN EXCLUDED.status = 'published' AND facebook_page_listings.published_at IS NULL THEN NOW()
        WHEN EXCLUDED.status <> 'published' THEN NULL
        ELSE facebook_page_listings.published_at
    END,
    updated_at = NOW()
WHERE facebook_page_listings.seller_user_id = EXCLUDED.seller_user_id
RETURNING id, page_id, seller_user_id, title, subtitle, description, price_usd::double precision AS price_usd,
          currency, delivery_window, status, featured, sort_order, created_at,
          updated_at, published_at
`

type UpsertFacebookPageListingParams struct {
	ID             uuid.UUID `json:"id"`
	PageID         uuid.UUID `json:"page_id"`
	SellerUserID   uuid.UUID `json:"seller_user_id"`
	Title          string    `json:"title"`
	Subtitle       string    `json:"subtitle"`
	Description    string    `json:"description"`
	Column7        float64   `json:"column_7"`
	Currency       string    `json:"currency"`
	DeliveryWindow string    `json:"delivery_window"`
	Status         string    `json:"status"`
	Featured       bool      `json:"featured"`
	SortOrder      int32     `json:"sort_order"`
}

type UpsertFacebookPageListingRow struct {
	ID             uuid.UUID          `json:"id"`
	PageID         uuid.UUID          `json:"page_id"`
	SellerUserID   uuid.UUID          `json:"seller_user_id"`
	Title          string             `json:"title"`
	Subtitle       string             `json:"subtitle"`
	Description    string             `json:"description"`
	PriceUsd       float64            `json:"price_usd"`
	Currency       string             `json:"currency"`
	DeliveryWindow string             `json:"delivery_window"`
	Status         string             `json:"status"`
	Featured       bool               `json:"featured"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpsertFacebookPageListing(ctx context.Context, arg UpsertFacebookPageListingParams) (UpsertFacebookPageListingRow, error) {
	row := q.db.QueryRow(ctx, upsertFacebookPageListing,
		arg.ID,
		arg.PageID,
		arg.SellerUserID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.Column7,
		arg.Currency,
		arg.DeliveryWindow,
		arg.Status,
		arg.Featured,
		arg.SortOrder,
	)
	var i UpsertFacebookPageListingRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.SellerUserID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.PriceUsd,
		&i.Currency,
		&i.DeliveryWindow,
		&i.Status,
		&i.Featured,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}
