// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facebook.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFacebookConnection = `-- name: DeleteFacebookConnection :exec
DELETE FROM facebook_connections
WHERE id = $1 AND user_id = $2
`

type DeleteFacebookConnectionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteFacebookConnection(ctx context.Context, arg DeleteFacebookConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteFacebookConnection, arg.ID, arg.UserID)
	return err
}

const getFacebookConnection = `-- name: GetFacebookConnection :one
SELECT id, user_id, facebook_user_id, facebook_user_name, encrypted_access_token,
       token_expires_at, scopes, created_at, updated_at, revoked_at
FROM facebook_connections
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type GetFacebookConnectionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetFacebookConnection(ctx context.Context, arg GetFacebookConnectionParams) (FacebookConnection, error) {
	row := q.db.QueryRow(ctx, getFacebookConnection, arg.ID, arg.UserID)
	var i FacebookConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacebookUserID,
		&i.FacebookUserName,
		&i.EncryptedAccessToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listFacebookConnections = `-- name: ListFacebookConnections :many
SELECT id, user_id, facebook_user_id, facebook_user_name, encrypted_access_token,
       token_expires_at, scopes, created_at, updated_at, revoked_at
FROM facebook_connections
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListFacebookConnections(ctx context.Context, userID uuid.UUID) ([]FacebookConnection, error) {
	rows, err := q.db.Query(ctx, listFacebookConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookConnection{}
	for rows.Next() {
		var i FacebookConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FacebookUserID,
			&i.FacebookUserName,
			&i.EncryptedAccessToken,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFacebookConnection = `-- name: UpsertFacebookConnection :one
INSERT INTO facebook_connections (
    id, user_id, facebook_user_id, facebook_user_name, encrypted_access_token,
    token_expires_at, scopes, revoked_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NULL)
ON CONFLICT (user_id, facebook_user_id) DO UPDATE
SET facebook_user_name = EXCLUDED.facebook_user_name,
    encrypted_access_token = EXCLUDED.encrypted_access_token,
    token_expires_at = EXCLUDED.token_expires_at,
    scopes = EXCLUDED.scopes,
    revoked_at = NULL,
    updated_at = NOW()
RETURNING id, user_id, facebook_user_id, facebook_user_name, encrypted_access_token,
          token_expires_at, scopes, created_at, updated_at, revoked_at
`

type UpsertFacebookConnectionParams struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	FacebookUserID       string             `json:"facebook_user_id"`
	FacebookUserName     string             `json:"facebook_user_name"`
	EncryptedAccessToken []byte             `json:"encrypted_access_token"`
	TokenExpiresAt       pgtype.Timestamptz `json:"token_expires_at"`
	Scopes               string             `json:"scopes"`
}

func (q *Queries) UpsertFacebookConnection(ctx context.Context, arg UpsertFacebookConnectionParams) (FacebookConnection, error) {
	row := q.db.QueryRow(ctx, upsertFacebookConnection,
		arg.ID,
		arg.UserID,
		arg.FacebookUserID,
		arg.FacebookUserName,
		arg.EncryptedAccessToken,
		arg.TokenExpiresAt,
		arg.Scopes,
	)
	var i FacebookConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacebookUserID,
		&i.FacebookUserName,
		&i.EncryptedAccessToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}
