// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error
	GetPasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error)
	GetSessionToken(ctx context.Context, tokenHash []byte) (GetSessionTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVerificationToken(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error)
	InvalidatePasswordResetTokens(ctx context.Context, userID uuid.UUID) error
	InvalidateVerificationTokens(ctx context.Context, userID uuid.UUID) error
	ListActiveSessions(ctx context.Context, userID uuid.UUID) ([]ListActiveSessionsRow, error)
	MarkPasswordResetTokenUsed(ctx context.Context, arg MarkPasswordResetTokenUsedParams) error
	MarkSessionTokenUsed(ctx context.Context, arg MarkSessionTokenUsedParams) error
	MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) error
	MarkVerificationTokenUsed(ctx context.Context, arg MarkVerificationTokenUsedParams) error
	RevokeAllSessions(ctx context.Context, userID uuid.UUID) error
	RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (pgconn.CommandTag, error)
	UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
