// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO auth_sessions (
    id, user_id, token_hash, user_agent, ip_address, expires_at, last_used_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSessionParams struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	UserAgent  string             `json:"user_agent"`
	IpAddress  string             `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const createSessionToken = `-- name: CreateSessionToken :exec
INSERT INTO auth_session_tokens (id, session_id, token_hash)
VALUES ($1, $2, $3)
`

type CreateSessionTokenParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	TokenHash []byte    `json:"token_hash"`
}

func (q *Queries) CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, createSessionToken, arg.ID, arg.SessionID, arg.TokenHash)
	return err
}

const getSessionToken = `-- name: GetSessionToken :one
SELECT
    s.id,
    s.user_id,
    s.token_hash,
    s.user_agent,
    s.ip_address,
    s.expires_at,
    s.last_used_at,
    s.created_at,
    s.revoked_at,
    t.token_hash AS presented_token_hash,
    t.used_at AS token_used_at,
    t.revoked_at AS token_revoked_at
FROM auth_session_tokens t
JOIN auth_sessions s ON s.id = t.session_id
WHERE t.token_hash = $1
FOR UPDATE OF s, t
`

type GetSessionTokenRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	TokenHash          []byte             `json:"token_hash"`
	UserAgent          string             `json:"user_agent"`
	IpAddress          string             `json:"ip_address"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	PresentedTokenHash []byte             `json:"presented_token_hash"`
	TokenUsedAt        pgtype.Timestamptz `json:"token_used_at"`
	TokenRevokedAt     pgtype.Timestamptz `json:"token_revoked_at"`
}

func (q *Queries) GetSessionToken(ctx context.Context, tokenHash []byte) (GetSessionTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionToken, tokenHash)
	var i GetSessionTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.PresentedTokenHash,
		&i.TokenUsedAt,
		&i.TokenRevokedAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, user_agent, ip_address, expires_at, last_used_at, created_at, revoked_at
FROM auth_sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > NOW()
ORDER BY last_used_at DESC
`

type ListActiveSessionsRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	UserAgent  string             `json:"user_agent"`
	IpAddress  string             `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListActiveSessions(ctx context.Context, userID uuid.UUID) ([]ListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSessionsRow{}
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionTokenUsed = `-- name: MarkSessionTokenUsed :exec
UPDATE auth_session_tokens
SET used_at = $3
WHERE session_id = $1 AND token_hash = $2 AND used_at IS NULL
`

type MarkSessionTokenUsedParams struct {
	SessionID uuid.UUID          `json:"session_id"`
	TokenHash []byte             `json:"token_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) MarkSessionTokenUsed(ctx context.Context, arg MarkSessionTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markSessionTokenUsed, arg.SessionID, arg.TokenHash, arg.UsedAt)
	return err
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, userID)
	return err
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :exec
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeOtherSessionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherSessions, arg.UserID, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :execresult
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE id = $1 AND user_id = $2
`

type RevokeUserSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, revokeUserSession, arg.ID, arg.UserID)
}

const updateSessionToken = `-- name: UpdateSessionToken :exec
UPDATE auth_sessions
SET token_hash = $2, last_used_at = $3
WHERE id = $1
`

type UpdateSessionTokenParams struct {
	ID         uuid.UUID          `json:"id"`
	TokenHash  []byte             `json:"token_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, updateSessionToken, arg.ID, arg.TokenHash, arg.LastUsedAt)
	return err
}
