// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordResetTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO email_verification_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateVerificationTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createVerificationToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM email_verification_tokens
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetVerificationToken(ctx context.Context, tokenHash []byte) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidatePasswordResetTokens = `-- name: InvalidatePasswordResetTokens :exec
UPDATE password_reset_tokens
SET used_at = COALESCE(used_at, NOW())
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidatePasswordResetTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePasswordResetTokens, userID)
	return err
}

const invalidateVerificationTokens = `-- name: InvalidateVerificationTokens :exec
UPDATE email_verification_tokens
SET used_at = COALESCE(used_at, NOW())
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateVerificationTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateVerificationTokens, userID)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens
SET used_at = $2
WHERE id = $1 AND used_at IS NULL
`

type MarkPasswordResetTokenUsedParams struct {
	ID     uuid.UUID          `json:"id"`
	UsedAt pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, arg MarkPasswordResetTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, arg.ID, arg.UsedAt)
	return err
}

const markVerificationTokenUsed = `-- name: MarkVerificationTokenUsed :exec
UPDATE email_verification_tokens
SET used_at = $2
WHERE id = $1 AND used_at IS NULL
`

type MarkVerificationTokenUsedParams struct {
	ID     uuid.UUID          `json:"id"`
	UsedAt pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) MarkVerificationTokenUsed(ctx context.Context, arg MarkVerificationTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markVerificationTokenUsed, arg.ID, arg.UsedAt)
	return err
}
