// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmWalletTopup = `-- name: ConfirmWalletTopup :one
UPDATE wallet_topups
SET status = 'confirmed',
    provider_transaction_id = COALESCE(NULLIF($2::varchar, ''), provider_transaction_id),
    paid_at = COALESCE(paid_at, NOW()),
    updated_at = NOW()
WHERE id = $1 AND status = 'pending_payment'
RETURNING id, wallet_id, user_id, reference,
          amount_usd::double precision AS amount_usd, currency, qr_payload, qr_md5,
          provider_transaction_id, status, failure_reason, resolution_note,
          expires_at, paid_at, created_at, updated_at
`

type ConfirmWalletTopupParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

type ConfirmWalletTopupRow struct {
	ID                    uuid.UUID          `json:"id"`
	WalletID              uuid.UUID          `json:"wallet_id"`
	UserID                uuid.UUID          `json:"user_id"`
	Reference             string             `json:"reference"`
	AmountUsd             float64            `json:"amount_usd"`
	Currency              string             `json:"currency"`
	QrPayload             string             `json:"qr_payload"`
	QrMd5                 string             `json:"qr_md5"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	Status                string             `json:"status"`
	FailureReason         string             `json:"failure_reason"`
	ResolutionNote        string             `json:"resolution_note"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ConfirmWalletTopup(ctx context.Context, arg ConfirmWalletTopupParams) (ConfirmWalletTopupRow, error) {
	row := q.db.QueryRow(ctx, confirmWalletTopup, arg.ID, arg.Column2)
	var i ConfirmWalletTopupRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UserID,
		&i.Reference,
		&i.AmountUsd,
		&i.Currency,
		&i.QrPayload,
		&i.QrMd5,
		&i.ProviderTransactionID,
		&i.Status,
		&i.FailureReason,
		&i.ResolutionNote,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countWalletTopupsAdmin = `-- name: CountWalletTopupsAdmin :one
SELECT COUNT(*)
FROM wallet_topups t
JOIN users u ON u.id = t.user_id
WHERE ($1::text = '' OR t.reference ILIKE '%' || $1::text || '%' OR u.email ILIKE '%' || $1::text || '%')
  AND ($2::varchar = '' OR t.status = $2::varchar)
`

type CountWalletTopupsAdminParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountWalletTopupsAdmin(ctx context.Context, arg CountWalletTopupsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTopupsAdmin, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWalletTopup = `-- name: CreateWalletTopup :one
INSERT INTO wallet_topups (
    id, wallet_id, user_id, reference, amount_usd, currency, qr_payload, qr_md5, expires_at
)
VALUES ($1, $2, $3, $4, $5::double precision, 'USD', $6::text, $7::varchar, $8::timestamptz)
RETURNING id, wallet_id, user_id, reference,
          amount_usd::double precision AS amount_usd, currency, qr_payload, qr_md5,
          provider_transaction_id, status, failure_reason, resolution_note,
          expires_at, paid_at, created_at, updated_at
`

type CreateWalletTopupParams struct {
	ID        uuid.UUID          `json:"id"`
	WalletID  uuid.UUID          `json:"wallet_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Reference string             `json:"reference"`
	Column5   float64            `json:"column_5"`
	Column6   string             `json:"column_6"`
	Column7   string             `json:"column_7"`
	Column8   pgtype.Timestamptz `json:"column_8"`
}

type CreateWalletTopupRow struct {
	ID                    uuid.UUID          `json:"id"`
	WalletID              uuid.UUID          `json:"wallet_id"`
	UserID                uuid.UUID          `json:"user_id"`
	Reference             string             `json:"reference"`
	AmountUsd             float64            `json:"amount_usd"`
	Currency              string             `json:"currency"`
	QrPayload             string             `json:"qr_payload"`
	QrMd5                 string             `json:"qr_md5"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	Status                string             `json:"status"`
	FailureReason         string             `json:"failure_reason"`
	ResolutionNote        string             `json:"resolution_note"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWalletTopup(ctx context.Context, arg CreateWalletTopupParams) (CreateWalletTopupRow, error) {
	row := q.db.QueryRow(ctx, createWalletTopup,
		arg.ID,
		arg.WalletID,
		arg.UserID,
		arg.Reference,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var i CreateWalletTopupRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UserID,
		&i.Reference,
		&i.AmountUsd,
		&i.Currency,
		&i.QrPayload,
		&i.QrMd5,
		&i.ProviderTransactionID,
		&i.Status,
		&i.FailureReason,
		&i.ResolutionNote,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditWallet = `-- name: CreditWallet :one
UPDATE wallets
SET available_amount = available_amount + $2::double precision,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, currency,
          available_amount::double precision AS available_amount,
          held_amount::double precision AS held_amount,
          created_at, updated_at
`

type CreditWalletParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 float64   `json:"column_2"`
}

type CreditWalletRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Currency        string             `json:"currency"`
	AvailableAmount float64            `json:"available_amount"`
	HeldAmount      float64            `json:"held_amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) (CreditWalletRow, error) {
	row := q.db.QueryRow(ctx, creditWallet, arg.ID, arg.Column2)
	var i CreditWalletRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableAmount,
		&i.HeldAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureWallet = `-- name: EnsureWallet :one
INSERT INTO wallets (id, user_id, currency)
VALUES ($1, $2, 'USD')
ON CONFLICT (user_id) DO UPDATE SET updated_at = wallets.updated_at
RETURNING id, user_id, currency,
          available_amount::double precision AS available_amount,
          held_amount::double precision AS held_amount,
          created_at, updated_at
`

type EnsureWalletParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type EnsureWalletRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Currency        string             `json:"currency"`
	AvailableAmount float64            `json:"available_amount"`
	HeldAmount      float64            `json:"held_amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) EnsureWallet(ctx context.Context, arg EnsureWalletParams) (EnsureWalletRow, error) {
	row := q.db.QueryRow(ctx, ensureWallet, arg.ID, arg.UserID)
	var i EnsureWalletRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableAmount,
		&i.HeldAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, currency,
       available_amount::double precision AS available_amount,
       held_amount::double precision AS held_amount,
       created_at, updated_at
FROM wallets
WHERE user_id = $1
`

type GetWalletRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Currency        string             `json:"currency"`
	AvailableAmount float64            `json:"available_amount"`
	HeldAmount      float64            `json:"held_amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWallet(ctx context.Context, userID uuid.UUID) (GetWalletRow, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i GetWalletRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableAmount,
		&i.HeldAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletAvailableBalance = `-- name: GetWalletAvailableBalance :one
SELECT available_amount::double precision AS available_amount
FROM wallets
WHERE user_id = $1 AND currency = 'USD'
`

func (q *Queries) GetWalletAvailableBalance(ctx context.Context, userID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getWalletAvailableBalance, userID)
	var available_amount float64
	err := row.Scan(&available_amount)
	return available_amount, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one
SELECT id, user_id, currency,
       available_amount::double precision AS available_amount,
       held_amount::double precision AS held_amount,
       created_at, updated_at
FROM wallets
WHERE id = $1
FOR UPDATE
`

type GetWalletForUpdateRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Currency        string             `json:"currency"`
	AvailableAmount float64            `json:"available_amount"`
	HeldAmount      float64            `json:"held_amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWalletForUpdate(ctx context.Context, id uuid.UUID) (GetWalletForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, id)
	var i GetWalletForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableAmount,
		&i.HeldAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTopup = `-- name: GetWalletTopup :one
SELECT id, wallet_id, user_id, reference,
       amount_usd::double precision AS amount_usd, currency, qr_payload, qr_md5,
       provider_transaction_id, status, failure_reason, resolution_note,
       expires_at, paid_at, created_at, updated_at
FROM wallet_topups
WHERE id = $1 AND user_id = $2
`

type GetWalletTopupParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetWalletTopupRow struct {
	ID                    uuid.UUID          `json:"id"`
	WalletID              uuid.UUID          `json:"wallet_id"`
	UserID                uuid.UUID          `json:"user_id"`
	Reference             string             `json:"reference"`
	AmountUsd             float64            `json:"amount_usd"`
	Currency              string             `json:"currency"`
	QrPayload             string             `json:"qr_payload"`
	QrMd5                 string             `json:"qr_md5"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	Status                string             `json:"status"`
	FailureReason         string             `json:"failure_reason"`
	ResolutionNote        string             `json:"resolution_note"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWalletTopup(ctx context.Context, arg GetWalletTopupParams) (GetWalletTopupRow, error) {
	row := q.db.QueryRow(ctx, getWalletTopup, arg.ID, arg.UserID)
	var i GetWalletTopupRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UserID,
		&i.Reference,
		&i.AmountUsd,
		&i.Currency,
		&i.QrPayload,
		&i.QrMd5,
		&i.ProviderTransactionID,
		&i.Status,
		&i.FailureReason,
		&i.ResolutionNote,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTopupByID = `-- name: GetWalletTopupByID :one
SELECT id, wallet_id, user_id, reference,
       amount_usd::double precision AS amount_usd, currency, qr_payload, qr_md5,
       provider_transaction_id, status, failure_reason, resolution_note,
       expires_at, paid_at, created_at, updated_at
FROM wallet_topups
WHERE id = $1
`

type GetWalletTopupByIDRow struct {
	ID                    uuid.UUID          `json:"id"`
	WalletID              uuid.UUID          `json:"wallet_id"`
	UserID                uuid.UUID          `json:"user_id"`
	Reference             string             `json:"reference"`
	AmountUsd             float64            `json:"amount_usd"`
	Currency              string             `json:"currency"`
	QrPayload             string             `json:"qr_payload"`
	QrMd5                 string             `json:"qr_md5"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	Status                string             `json:"status"`
	FailureReason         string             `json:"failure_reason"`
	ResolutionNote        string             `json:"resolution_note"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWalletTopupByID(ctx context.Context, id uuid.UUID) (GetWalletTopupByIDRow, error) {
	row := q.db.QueryRow(ctx, getWalletTopupByID, id)
	var i GetWalletTopupByIDRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UserID,
		&i.Reference,
		&i.AmountUsd,
		&i.Currency,
		&i.QrPayload,
		&i.QrMd5,
		&i.ProviderTransactionID,
		&i.Status,
		&i.FailureReason,
		&i.ResolutionNote,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTopupByMD5 = `-- name: GetWalletTopupByMD5 :one
SELECT id, wallet_id, user_id, reference,
       amount_usd::double precision AS amount_usd, currency, qr_payload, qr_md5,
       provider_transaction_id, status, failure_reason, resolution_note,
       expires_at, paid_at, created_at, updated_at
FROM wallet_topups
WHERE qr_md5 = $1
`

type GetWalletTopupByMD5Row struct {
	ID                    uuid.UUID          `json:"id"`
	WalletID              uuid.UUID          `json:"wallet_id"`
	UserID                uuid.UUID          `json:"user_id"`
	Reference             string             `json:"reference"`
	AmountUsd             float64            `json:"amount_usd"`
	Currency              string             `json:"currency"`
	QrPayload             string             `json:"qr_payload"`
	QrMd5                 string             `json:"qr_md5"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	Status                string             `json:"status"`
	FailureReason         string             `json:"failure_reason"`
	ResolutionNote        string             `json:"resolution_note"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWalletTopupByMD5(ctx context.Context, qrMd5 string) (GetWalletTopupByMD5Row, error) {
	row := q.db.QueryRow(ctx, getWalletTopupByMD5, qrMd5)
	var i GetWalletTopupByMD5Row
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UserID,
		&i.Reference,
		&i.AmountUsd,
		&i.Currency,
		&i.QrPayload,
		&i.QrMd5,
		&i.ProviderTransactionID,
		&i.Status,
		&i.FailureReason,
		&i.ResolutionNote,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTopupByReference = `-- name: GetWalletTopupByReference :one
SELECT id, wallet_id, user_id, reference,
       amount_usd::double precision AS amount_usd, currency, qr_payload, qr_md5,
       provider_transaction_id, status, failure_reason, resolution_note,
       expires_at, paid_at, created_at, updated_at
FROM wallet_topups
WHERE reference = $1
`

type GetWalletTopupByReferenceRow struct {
	ID                    uuid.UUID          `json:"id"`
	WalletID              uuid.UUID          `json:"wallet_id"`
	UserID                uuid.UUID          `json:"user_id"`
	Reference             string             `json:"reference"`
	AmountUsd             float64            `json:"amount_usd"`
	Currency              string             `json:"currency"`
	QrPayload             string             `json:"qr_payload"`
	QrMd5                 string             `json:"qr_md5"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	Status                string             `json:"status"`
	FailureReason         string             `json:"failure_reason"`
	ResolutionNote        string             `json:"resolution_note"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWalletTopupByReference(ctx context.Context, reference string) (GetWalletTopupByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getWalletTopupByReference, reference)
	var i GetWalletTopupByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UserID,
		&i.Reference,
		&i.AmountUsd,
		&i.Currency,
		&i.QrPayload,
		&i.QrMd5,
		&i.ProviderTransactionID,
		&i.Status,
		&i.FailureReason,
		&i.ResolutionNote,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTopupForUpdate = `-- name: GetWalletTopupForUpdate :one
SELECT id, wallet_id, user_id, reference,
       amount_usd::double precision AS amount_usd, currency, qr_payload, qr_md5,
       provider_transaction_id, status, failure_reason, resolution_note,
       expires_at, paid_at, created_at, updated_at
FROM wallet_topups
WHERE id = $1
FOR UPDATE
`

type GetWalletTopupForUpdateRow struct {
	ID                    uuid.UUID          `json:"id"`
	WalletID              uuid.UUID          `json:"wallet_id"`
	UserID                uuid.UUID          `json:"user_id"`
	Reference             string             `json:"reference"`
	AmountUsd             float64            `json:"amount_usd"`
	Currency              string             `json:"currency"`
	QrPayload             string             `json:"qr_payload"`
	QrMd5                 string             `json:"qr_md5"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	Status                string             `json:"status"`
	FailureReason         string             `json:"failure_reason"`
	ResolutionNote        string             `json:"resolution_note"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWalletTopupForUpdate(ctx context.Context, id uuid.UUID) (GetWalletTopupForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWalletTopupForUpdate, id)
	var i GetWalletTopupForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UserID,
		&i.Reference,
		&i.AmountUsd,
		&i.Currency,
		&i.QrPayload,
		&i.QrMd5,
		&i.ProviderTransactionID,
		&i.Status,
		&i.FailureReason,
		&i.ResolutionNote,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWalletLedgerEntry = `-- name: InsertWalletLedgerEntry :exec
INSERT INTO wallet_ledger_entries (
    id, wallet_id, user_id, entry_type, reference,
    available_delta_usd, held_delta_usd,
    available_balance_usd, held_balance_usd, description
)
VALUES ($1, $2, $3, $4::varchar, $5::varchar, $6::double precision, $7::double precision,
        $8::double precision, $9::double precision, $10::text)
`

type InsertWalletLedgerEntryParams struct {
	ID       uuid.UUID `json:"id"`
	WalletID uuid.UUID `json:"wallet_id"`
	UserID   uuid.UUID `json:"user_id"`
	Column4  string    `json:"column_4"`
	Column5  string    `json:"column_5"`
	Column6  float64   `json:"column_6"`
	Column7  float64   `json:"column_7"`
	Column8  float64   `json:"column_8"`
	Column9  float64   `json:"column_9"`
	Column10 string    `json:"column_10"`
}

func (q *Queries) InsertWalletLedgerEntry(ctx context.Context, arg InsertWalletLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertWalletLedgerEntry,
		arg.ID,
		arg.WalletID,
		arg.UserID,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
	)
	return err
}

const listWalletLedger = `-- name: ListWalletLedger :many
SELECT id, wallet_id, user_id, entry_type, reference,
       available_delta_usd::double precision AS available_delta_usd,
       held_delta_usd::double precision AS held_delta_usd,
       available_balance_usd::double precision AS available_balance_usd,
       held_balance_usd::double precision AS held_balance_usd,
       description, created_at
FROM wallet_ledger_entries
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListWalletLedgerParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListWalletLedgerRow struct {
	ID                  uuid.UUID          `json:"id"`
	WalletID            uuid.UUID          `json:"wallet_id"`
	UserID              uuid.UUID          `json:"user_id"`
	EntryType           string             `json:"entry_type"`
	Reference           string             `json:"reference"`
	AvailableDeltaUsd   float64            `json:"available_delta_usd"`
	HeldDeltaUsd        float64            `json:"held_delta_usd"`
	AvailableBalanceUsd float64            `json:"available_balance_usd"`
	HeldBalanceUsd      float64            `json:"held_balance_usd"`
	Description         string             `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWalletLedger(ctx context.Context, arg ListWalletLedgerParams) ([]ListWalletLedgerRow, error) {
	rows, err := q.db.Query(ctx, listWalletLedger, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletLedgerRow{}
	for rows.Next() {
		var i ListWalletLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.UserID,
			&i.EntryType,
			&i.Reference,
			&i.AvailableDeltaUsd,
			&i.HeldDeltaUsd,
			&i.AvailableBalanceUsd,
			&i.HeldBalanceUsd,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTopupsAdmin = `-- name: ListWalletTopupsAdmin :many
SELECT t.id, t.wallet_id, t.user_id, u.name AS user_name, u.email AS user_email,
       t.reference, t.amount_usd::double precision AS amount_usd, t.currency,
       t.qr_md5, t.provider_transaction_id, t.status, t.failure_reason,
       t.resolution_note, t.expires_at, t.paid_at, t.created_at, t.updated_at
FROM wallet_topups t
JOIN users u ON u.id = t.user_id
WHERE ($1::text = '' OR t.reference ILIKE '%' || $1::text || '%' OR u.email ILIKE '%' || $1::text || '%')
  AND ($2::varchar = '' OR t.status = $2::varchar)
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $4
`

type ListWalletTopupsAdminParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListWalletTopupsAdminRow struct {
	ID                    uuid.UUID          `json:"id"`
	WalletID              uuid.UUID          `json:"wallet_id"`
	UserID                uuid.UUID          `json:"user_id"`
	UserName              string             `json:"user_name"`
	UserEmail             string             `json:"user_email"`
	Reference             string             `json:"reference"`
	AmountUsd             float64            `json:"amount_usd"`
	Currency              string             `json:"currency"`
	QrMd5                 string             `json:"qr_md5"`
	ProviderTransactionID pgtype.Text        `json:"provider_transaction_id"`
	Status                string             `json:"status"`
	FailureReason         string             `json:"failure_reason"`
	ResolutionNote        string             `json:"resolution_note"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWalletTopupsAdmin(ctx context.Context, arg ListWalletTopupsAdminParams) ([]ListWalletTopupsAdminRow, error) {
	rows, err := q.db.Query(ctx, listWalletTopupsAdmin,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletTopupsAdminRow{}
	for rows.Next() {
		var i ListWalletTopupsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.Reference,
			&i.AmountUsd,
			&i.Currency,
			&i.QrMd5,
			&i.ProviderTransactionID,
			&i.Status,
			&i.FailureReason,
			&i.ResolutionNote,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWalletTopupExpired = `-- name: MarkWalletTopupExpired :exec
UPDATE wallet_topups
SET status = 'expired', failure_reason = 'QR expired before payment was verified', updated_at = NOW()
WHERE id = $1 AND status = 'pending_payment'
`

func (q *Queries) MarkWalletTopupExpired(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWalletTopupExpired, id)
	return err
}

const markWalletTopupFailed = `-- name: MarkWalletTopupFailed :exec
UPDATE wallet_topups
SET status = 'failed', failure_reason = $2::text, updated_at = NOW()
WHERE id = $1 AND status = 'pending_payment'
`

type MarkWalletTopupFailedParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) MarkWalletTopupFailed(ctx context.Context, arg MarkWalletTopupFailedParams) error {
	_, err := q.db.Exec(ctx, markWalletTopupFailed, arg.ID, arg.Column2)
	return err
}
